[project]
name = "yuvalavraham"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "requests>=2.32.4",
    "tqdm>=4.66.4",
    "transformers>=4.44.2",
    "torch>=2.4.0",
    "torchaudio>=2.4.0",
    "soundfile>=0.12.1",
]
